# Generated by Django 5.0.2 on 2024-02-29 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=20)),
                ('skills', models.TextField()),
            ],
            options={
                'verbose_name_plural': '1. Academics',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=200)),
                ('interested_module', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('module_views', models.BigIntegerField(default=0)),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_modules', to='modapp.academic')),
            ],
            options={
                'verbose_name_plural': '3. Modules',
            },
        ),
        migrations.CreateModel(
            name='StudentModuleEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_time', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_academic', to='modapp.academic')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_modules', to='modapp.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_student', to='modapp.student')),
            ],
            options={
                'verbose_name_plural': '5. Enrolled modules',
            },
        ),
        migrations.CreateModel(
            name='StudentModuleAcademic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
                ('mark_time', models.DateTimeField(auto_now_add=True)),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentenrolled_academics', to='modapp.academic')),
                ('student_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentenrolled_modules', to='modapp.studentmoduleenrollment')),
            ],
            options={
                'verbose_name_plural': '6. Student enrolledModule',
            },
        ),
    ]
